# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ca215a7fd3b6850693a5b19b72a901a69acdb15807c32c9beccb13e8025f09483e487625a949fdd763da99d369227db064b2a177629995384dcb19b993fe1bf

test:
  secret_key_base: 37d57e85b3b92ee937a47974748e261114998f002de50607b8d20ed6313e6407bd1bedf9c4df3a2557491992393ce17795396a60a0e2c9013e8c53fb82a3d257

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
